import { z } from "zod";

const latLngArraySchema = z.array(z.number());

const metaAthleteSchema = z
  .object({
    id: z.number(),
  });

export const sportTypeSchema = z.union([
  z.literal("AlpineSki"),
  z.literal("BackcountrySki"),
  z.literal("Badminton"),
  z.literal("Canoeing"),
  z.literal("Crossfit"),
  z.literal("EBikeRide"),
  z.literal("Elliptical"),
  z.literal("EMountainBikeRide"),
  z.literal("Golf"),
  z.literal("GravelRide"),
  z.literal("Handcycle"),
  z.literal("HighIntensityIntervalTraining"),
  z.literal("Hike"),
  z.literal("IceSkate"),
  z.literal("InlineSkate"),
  z.literal("Kayaking"),
  z.literal("Kitesurf"),
  z.literal("MountainBikeRide"),
  z.literal("NordicSki"),
  z.literal("Pickleball"),
  z.literal("Pilates"),
  z.literal("Racquetball"),
  z.literal("Ride"),
  z.literal("RockClimbing"),
  z.literal("RollerSki"),
  z.literal("Rowing"),
  z.literal("Run"),
  z.literal("Sail"),
  z.literal("Skateboard"),
  z.literal("Snowboard"),
  z.literal("Snowshoe"),
  z.literal("Soccer"),
  z.literal("Squash"),
  z.literal("StairStepper"),
  z.literal("StandUpPaddling"),
  z.literal("Surfing"),
  z.literal("Swim"),
  z.literal("TableTennis"),
  z.literal("Tennis"),
  z.literal("TrailRun"),
  z.literal("Velomobile"),
  z.literal("VirtualRide"),
  z.literal("VirtualRow"),
  z.literal("VirtualRun"),
  z.literal("Walk"),
  z.literal("WeightTraining"),
  z.literal("Wheelchair"),
  z.literal("Windsurf"),
  z.literal("Workout"),
  z.literal("Yoga"),
]);

export const polylineMapSchema = z
  .object({
    id: z.string(),
    polyline: z.string().optional(),
    summary_polyline: z.string(),
  });

export const activitySummarySchema = z.object({
  id: z.number(),
  external_id: z.string(),
  upload_id: z.number(),
  athlete: metaAthleteSchema,
  name: z.string(),
  distance: z.number(),
  moving_time: z.number(),
  elapsed_time: z.number(),
  total_elevation_gain: z.number(),
  elev_high: z.number(),
  elev_low: z.number(),
  sport_type: sportTypeSchema,
  start_date: z.string(),
  start_date_local: z.string(),
  timezone: z.string(),
  start_latlng: latLngArraySchema,
  end_latlng: latLngArraySchema,
  achievement_count: z.number(),
  kudos_count: z.number(),
  comment_count: z.number(),
  athlete_count: z.number(),
  photo_count: z.number(),
  total_photo_count: z.number(),
  map: polylineMapSchema.optional(),
  trainer: z.boolean(),
  commute: z.boolean(),
  manual: z.boolean(),
  private: z.boolean(),
  flagged: z.boolean(),
  workout_type: z.number().nullish(),
  upload_id_str: z.string(),
  average_speed: z.number(),
  max_speed: z.number(),
  has_kudoed: z.boolean(),
  gear_id: z.string().nullish(),
  kilojoules: z.number().optional(),
  average_watts: z.number().optional(),
  device_watts: z.boolean().optional(),
  max_watts: z.number().optional(),
  weighted_average_watts: z.number().optional(),
});

export const getActivitiesResponseSchema = z.array(activitySummarySchema);
